language: ruby
rvm:
 - 2.7

sudo: false
cache: bundler
gemfile: Gemfile

branches:
  only:
    - main

notifications:
  email: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_script:
 - chmod +x ./script/cibuild
 - chmod +x ./script/sitemap_ping

script: ./script/cibuild

deploy:
  strategy: git
  provider: pages
  target_branch: gh-pages
  cleanup: false
  token: $GITHUB_TOKEN
  committer_from_gh: true
  keep_history: true
  verbose: true
  on:
    branch: main

after_deploy: ./script/sitemap_ping
