#!/usr/bin/env bash
set -e # halt script on error

echo
echo "--------------------------------------------------------------------------------"
if [ "$TRAVIS_PULL_REQUEST" != "false" -a "$TRAVIS_BRANCH" == "comments" ]; then

    echo
    echo "Building site for pull request for $TRAVIS_BRANCH..."
    bundle exec jekyll build --config _config.yml --source . --destination ./docs
    echo "Site built into /docs"

    echo
    echo "Proofing links"
    bundle exec htmlproofer ./docs --disable-external --allow_hash_href
    echo "Proofing links complete"
    echo
    echo "--------------------------------------------------------------------------------"

    exit 0

elif [ "$TRAVIS_BRANCH" == "master" ]; then

    echo
    echo "Building site for $TRAVIS_BRANCH..."
    bundle exec jekyll build --config _config.yml --source . --destination ./docs
    echo "Site built into /docs"

    echo
    echo "Proofing links"
    bundle exec htmlproofer ./docs --disable-external --allow_hash_href
    echo "Proofing links complete"
    echo
    echo "--------------------------------------------------------------------------------"

    exit 0

else

    echo
    echo "Build not triggered internally"
    echo
    echo "--------------------------------------------------------------------------------"
    exit 0

fi

